# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class Test010SEIModWsseiSIP():
  def setup_method(self, method):
    self.driver = webdriver.Remote(command_executor='http://seleniumhub:4444/wd/hub', desired_capabilities=DesiredCapabilities.CHROME)
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_criarUsuarios(self):
    self.driver.get("http://sei3.nuvem.gov.br/sip/login.php?sigla_orgao_sistema=ME&sigla_sistema=SIP&infra_url=L3NpcC8=")
    self.driver.find_element(By.ID, "txtUsuario").click()
    self.driver.find_element(By.ID, "txtUsuario").send_keys("teste")
    self.driver.find_element(By.ID, "pwdSenha").click()
    self.driver.find_element(By.ID, "pwdSenha").send_keys("teste")
    self.driver.find_element(By.ID, "sbmLogin").click()
    self.driver.find_element(By.XPATH, "//*[@id=\"main-menu\"]/li[6]/a").click()
    self.driver.find_element(By.LINK_TEXT, "Novo").click()
    self.driver.find_element(By.ID, "divInfraAreaDados").click()
    self.driver.find_element(By.ID, "selOrgao").click()
    dropdown = self.driver.find_element(By.ID, "selOrgao")
    dropdown.find_element(By.XPATH, "//option[. = 'ME']").click()
    self.driver.find_element(By.ID, "selOrgao").click()
    self.driver.find_element(By.ID, "txtSigla").click()
    self.driver.find_element(By.ID, "txtSigla").send_keys("usuario1")
    self.driver.find_element(By.ID, "txtNome").click()
    self.driver.find_element(By.ID, "txtNome").send_keys("Usuario de Teste 1")
    self.driver.find_element(By.NAME, "sbmCadastrarUsuario").click()
    self.driver.find_element(By.XPATH, "//*[@id=\"main-menu\"]/li[6]/a").click()
    self.driver.find_element(By.LINK_TEXT, "Novo").click()
    self.driver.find_element(By.ID, "txtSigla").click()
    self.driver.find_element(By.ID, "txtSigla").send_keys("usuario2")
    self.driver.find_element(By.ID, "txtNome").click()
    self.driver.find_element(By.ID, "txtNome").send_keys("Usuario de Teste 2")
    self.driver.find_element(By.NAME, "sbmCadastrarUsuario").click()
    self.driver.find_element(By.CSS_SELECTOR, "#lnkSairSistema > .infraImg").click()
    self.driver.close()
  
  def test_unidadesCadastrarMontarHierarquia(self):
    self.driver.get("http://sei3.nuvem.gov.br/sip/login.php?sigla_orgao_sistema=ME&sigla_sistema=SIP&infra_url=L3NpcC8=")
    self.driver.find_element(By.ID, "txtUsuario").click()
    self.driver.find_element(By.ID, "txtUsuario").send_keys("teste")
    self.driver.find_element(By.ID, "pwdSenha").click()
    self.driver.find_element(By.ID, "pwdSenha").send_keys("teste")
    self.driver.find_element(By.ID, "sbmLogin").click()
    for i in range(0, 40):
      self.driver.find_element(By.XPATH, "//*[@id=\"main-menu\"]/li[8]/a").click()
      self.driver.find_element(By.LINK_TEXT, "Nova").click()
      self.driver.find_element(By.ID, "selOrgao").click()
      dropdown = self.driver.find_element(By.ID, "selOrgao")
      dropdown.find_element(By.XPATH, "//option[. = 'ME']").click()
      self.driver.find_element(By.ID, "selOrgao").click()
      self.driver.find_element(By.ID, "txtSigla").click()
      self.vars["data"] = self.driver.execute_script("var d= new Date(); var m=((d.getMonth()+1)<10)?\'0\'+(d.getMonth()+1):(d.getMonth()+1); return d.getFullYear()+\'-\'+m+\'-\'+d.getDate();")
      self.vars["hora"] = self.driver.execute_script("return (new Date().getHours()+\'-\' + new Date().getMinutes() + \'-\' + new Date().getSeconds())")
      self.driver.find_element(By.ID, "txtSigla").send_keys("Un-" + self.vars["data"] + "-" + self.vars["hora"])
      self.driver.find_element(By.ID, "divInfraAreaDados").click()
      self.driver.find_element(By.ID, "txtDescricao").click()
      self.driver.find_element(By.ID, "txtDescricao").send_keys("Unidade " + self.vars["data"] + self.vars["hora"])
      self.driver.find_element(By.NAME, "sbmCadastrarUnidade").click()
      self.driver.find_element(By.XPATH, "//*[@id=\"main-menu\"]/li[7]/a").click()
      self.driver.find_element(By.LINK_TEXT, "Montar").click()
      self.driver.find_element(By.ID, "selHierarquia").click()
      dropdown = self.driver.find_element(By.ID, "selHierarquia")
      dropdown.find_element(By.XPATH, "//option[. = 'SEI']").click()
      self.driver.find_element(By.ID, "selHierarquia").click()
      self.driver.find_element(By.ID, "btnNova").click()
      self.driver.find_element(By.ID, "selUnidade").click()
      dropdown = self.driver.find_element(By.ID, "selUnidade")
      dropdown.find_element(By.XPATH, "//option[. = 'Un-" + self.vars["data"] + "-" + self.vars["hora"] + "']").click()
      self.driver.find_element(By.ID, "selUnidade").click()
      self.driver.find_element(By.ID, "imgCalDataInicio").click()
      self.driver.find_element(By.CSS_SELECTOR, ".activeDay").click()
      self.driver.find_element(By.NAME, "sbmCadastrarHierarquiaUnidade").click()
      time.sleep(1)
    self.driver.find_element(By.CSS_SELECTOR, "#lnkSairSistema > .infraImg").click()
    self.driver.close()
  
