<div class="row">
    <div class="col-md-12 padding-0">
        <div class="rastro">
            <a href="index.html">Home</a><i class="fa fa-angle-right"></i>
            <a href="" class="active">Javascript</a>
        </div>
    </div>
</div>

<h2>Javascript</h2>

<p>Referencia de Plugins e elementos utilizados no sistema.</p>

<div class="caixa-centro sp-10">
    <div class="col-md-12 pln">
        <h2 class="col-md-6 pull-left">Validação de Campos</h2>
    </div>
    <p class="col-md-12">Plugin de validação de campos : <a href="http://1000hz.github.io/bootstrap-validator/" target="blank">Jquery Validation</a></p>
</div> <!-- Final caixa centro -->

<div class="caixa-centro sp-10">
    <div class="col-md-12 pln">
        <h2 class="col-md-6 pull-left">Mascara de Campos</h2>
    </div>

    <p class="col-md-12">Mascara de campos : <a href="http://igorescobar.github.io/jQuery-Mask-Plugin/" target="blank">Jquery Mask Plugin</a></p>
</div> <!-- Final caixa centro -->

<div class="caixa-centro sp-10">
    <div class="col-md-12 pln">
        <h2 class="col-md-6 pull-left">Datetimepicker</h2>
    </div>
    <p class="col-md-12">Plugin de Data e Hora : <a href="http://eonasdan.github.io/bootstrap-datetimepicker/" target="blank">Datetimepicker</a></p>
    <p class="col-md-12">Validação Data e Hora : <a href="http://momentjs.com/" target="blank">Moment</a></p>
</div> <!-- Final caixa centro -->

<div class="caixa-centro sp-10">
    <div class="col-md-12 pln">
        <h2 class="col-md-6 pull-left">Datatables</h2>
    </div>
    <p class="col-md-12">Tabela com filtros e paginação: <a href="http://www.datatables.net/" target="blank">Datatables</a></p>
</div> <!-- Final caixa centro -->

<div class="caixa-centro sp-10">
    <div class="col-md-12 pln">
        <h2 class="col-md-6 pull-left">Summernote</h2>
    </div>
    <p class="col-md-12">Barra de Ferramentas (WYSIWYG Editor): <a href="http://summernote.org/" target="blank">Summernote</a></p>
</div> <!-- Final caixa centro -->

<div class="caixa-centro sp-10">
    <div class="col-md-12 pln">
        <h2 class="col-md-6 pull-left">Multi Select</h2>
    </div>
    <p class="col-md-12">Seletor multiplo:<a href="http://hemantnegi.github.io/jquery.sumoselect/" target="blank">Multi Select plugin</a></p>
</div> <!-- Final caixa centro -->
