<h2>Acesso SSD</h2>

<div class="col-md-6 col-xs-12">
    <p><strong>Parágrafo</strong> Lorem ipsum dolor sit amet, consectetur adipisicing elit. Aliquos mel miseram principio fonte o dicturam. Satisfacit gravissimis uterque, occultarum mundus mala praetore progrediens ibidem respirare imbutus, praetermissum optari dubio derepta desideraturam aegritudo quales. Rem facile nosmet quoddam. Geometria fruentem parta. Sic, voluptatibus torquate rationem, quidem triario impendere dulce, recordatione, faciunt defuturum sensuum, coniuncta, facile consequentium suavitate feci dicitis detrimenti..</p>
    <div class="row">
        <button type="button" class="btn  btn-default"><i class="fa fa fa-download"></i> Download do Edital 01</button>
        <button type="button" class="btn  btn-default"><i class="fa fa fa-download"></i> Download do Edital 02</button>
    </div>
</div>

<div class="row caixa-login col-md-5 col-xs-12 sombra-2 col-md-offset-1 ">

    <div class="row">
        <div class="col-md-12">
            <h3>Já sou cadastrado</h3>
            <a href="/login/redirect-login-ssd"><button type="button" class="btn btn-primary btn-block"><i class="fa fa-check"></i> Entrar</button></a>
        </div>
    </div>

    <div class="col-md-12 sp-20">
        <div class="separador"></div>
        <h3>Solicitar cadastro</h3>
        <a href="#"><button type="button" class="btn btn-success btn-block"><i class="fa fa-pencil-square-o"></i> Solicitar Acesso</button></a>
    </div>
</div>
