<h2><?php echo $this->titulo; ?></h2>
<?php $form->prepare();  ?>
<?php echo $this->form()->openTag($form); ?>
    <div class="form-element">
        <?php $fileElement = $form->get('arquivo'); ?>
        <?php echo $this->formElementErrors($fileElement); ?>
        <?php echo $this->formLabel($fileElement); ?>
        <?php echo $this->formFile($fileElement); ?>
        <?php echo $this->FormElement($form->get('btnSubmit')); ?>
    </div>
<?php echo $this->form()->closeTag(); ?>
