<?php

namespace Application\Entity\Repository;

use Base\Entity\Repository\AbstractEntityRepository;
use Application;

/**
 * AcompanhamentoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AcompanhamentoRepository extends AbstractEntityRepository
{
    public function maxAcompanhamento() {
        $qb = $this->_em->createQueryBuilder();

        $qb->select('MAX(a.idAcompanhamento) AS id')
            ->from('Application\Entity\Acompanhamento', 'a');

        return $qb->getQuery()->getArrayResult();
    }
}
