<?php

namespace Application\Entity\Repository;

use Base\Entity\Repository\AbstractEntityRepository;
use Application;

/**
 * AnexoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AnexoRepository extends AbstractEntityRepository
{
    public function pesquisarAnexoPorProtocolo ($protocolo) {
        $qb = $this->_em->createQueryBuilder();

        $qb->select('A')
            ->from('Application\Entity\Anexo', 'A')
            ->where('A.idProtocolo = :protocolo')
            ->andWhere('A.sinAtivo = :ativo')
            ->setParameter('protocolo', $protocolo)
            ->setParameter('ativo', 'S');

        return $qb->getQuery()->getResult();
    }
}
