<?php

namespace Application\Entity\Repository;

use Base\Entity\Repository\AbstractEntityRepository;
use Application;
use Application\Entity\Protocolo;

/**
 * AnotacaoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AnotacaoRepository extends AbstractEntityRepository
{
    public function pesquisarAnotacaoPorProtocolo (Protocolo $protocolo, $unidade) {
        $qb = $this->createQueryBuilder('P');

        $qb->where('P.idProtocolo = :protocolo')
           ->setParameter('protocolo', $protocolo);

        $qb->andWhere('P.idUnidade = :unidade ')
            ->setParameter('unidade', $unidade);

        return $qb->getQuery()->getArrayResult();
    }

    public function maxAnotacao() {
        $id = 0;
        $qb = $this->_em->createQueryBuilder();

        $qb->select('MAX(a.idAnotacao) AS id')
            ->from('Application\Entity\Anotacao', 'a');

        $result = $qb->getQuery()->getArrayResult();

        if (count($result) > 0)
            $id = $result[0]['id'];

        return $id;
    }
}
