<?php

namespace Application\Entity\Repository;

use Base\Entity\Repository\AbstractEntityRepository;
use Application;

/**
 * AssinanteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AssinanteRepository extends AbstractEntityRepository
{

    public function listarCargoFuncao ($unidade, $limit, $offset) {
        $qb = $this->_em->createQueryBuilder();

        $qb->select('A.idAssinante, A.cargoFuncao ')
            ->from('Application\Entity\RelAssinanteUnidade', 'AU')
            ->join('AU.idAssinante', 'A')
            ->where('AU.idUnidade = :unidade')
            ->setParameter('unidade', $unidade);

        $result = $qb->getQuery()->getArrayResult();

        return array('result' => $result);
    }
}
