<?php

namespace Application\Entity\Repository;

use Base\Entity\Repository\AbstractEntityRepository;
use Application;
use Doctrine\ORM\Tools\Pagination\Paginator;

/**
 * CargoFuncaoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CargoFuncaoRepository extends AbstractEntityRepository
{
    public function listarCargoFuncao ($unidade, $limit, $offset) {
        $qb = $this->_em->createQueryBuilder();

        $qb->select('CF')
            ->from('Application\Entity\CargoFuncao', 'CF')
            ->where('CF.idUnidade = :unidade')
            ->andWhere('CF.sinAtivo = :ativo')
            ->setParameter('unidade', $unidade)
            ->setParameter('ativo', 'S');

        $qb->setFirstResult($offset)
            ->setMaxResults($limit);

        $paginator = new Paginator($qb, true);

        return array('result' => $paginator->getQuery()->getResult(), 'count' => $paginator->count());
    }
}
