<?php

namespace Application\Entity\Repository;

use Base\Entity\Repository\AbstractEntityRepository;
use Application;
use Doctrine\ORM\Tools\Pagination\Paginator;

/**
 * GrupoAcompanhamentoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GrupoAcompanhamentoRepository extends AbstractEntityRepository
{
    public function listarGrupoAcompanhamento ($unidade, $limit, $offset) {
        $qb = $this->_em->createQueryBuilder();

        $qb->select('GA')
            ->from('Application\Entity\GrupoAcompanhamento', 'GA')
            ->addOrderBy('GA.nome');

        if ($unidade) {
            $qb->where('GA.idUnidade = :unidade')
               ->setParameter('unidade', $unidade);
        }

        $qb->setFirstResult($offset)
            ->setMaxResults($limit);

        $paginator = new Paginator($qb, true);

        return array('result' => $paginator->getQuery()->getResult(), 'count' => $paginator->count());
    }
}
