<?php

namespace Application\Entity\Repository;

use Base\Entity\Repository\AbstractEntityRepository;
use Application;
use Doctrine\Common\Util\Debug;

/**
 * InfraDadoUsuarioRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class InfraDadoUsuarioRepository extends AbstractEntityRepository
{
    public function getUnidadePorUsuario($usuario) {
        $qb = $this->_em->createQueryBuilder();

        $qb->select('u.valor')
            ->from('Application\Entity\InfraDadoUsuario', 'u');
        $qb->where('u.idUsuario = :usuario')
            ->andWhere('u.nome = :nome')
            ->setParameter('nome', 'INFRA_UNIDADE_ATUAL')
            ->setParameter('usuario', $usuario);

        return $qb->getQuery()->getResult();
    }
}
