<?php

namespace Application\Entity\Repository;

use Base\Entity\Repository\AbstractEntityRepository;
use Application;

/**
 * ObservacaoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ObservacaoRepository extends AbstractEntityRepository
{
    public function maxObservacao() {
        $id = 0;
        $qb = $this->_em->createQueryBuilder();

        $qb->select('MAX(o.idObservacao) AS id')
            ->from('Application\Entity\Observacao', 'o');

        $result = $qb->getQuery()->getArrayResult();

        if (count($result))
            $id = $result[0]['id'];

        return $id;
    }
}
