<?php

namespace Application\Entity\Repository;

use Base\Entity\Repository\AbstractEntityRepository;
use Application;

/**
 * ProtocoloRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProtocoloRepository extends AbstractEntityRepository
{
    public function pesquisarProtocolo($protocolo)
    {
        $qb = $this->_em->createQueryBuilder();

        $qb->select('p')
            ->from('Application\Entity\Protocolo', 'p')
            ->where('p.idProtocolo = :protocolo')
            ->setParameter('protocolo', $protocolo);

        return $qb->getQuery()->getResult();
    }
}
