<?php

namespace Application\Entity\Repository;

use Base\Entity\Repository\AbstractEntityRepository;
use Application;
use Application\Entity\Documento;

/**
 * PublicacaoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PublicacaoRepository extends AbstractEntityRepository
{
    public function pesquisarPublicacaoPorDocumento (Documento $documento) {
        $qb = $this->createQueryBuilder('P');

        $qb->where('P.idDocumento = :documento')
           ->setParameter('documento', $documento);

        return $qb->getQuery()->getResult();
    }
}
