<?php

namespace Application\Entity\Repository;

use Base\Entity\Repository\AbstractEntityRepository;
use Application;
use Doctrine\ORM\Tools\Pagination\Paginator;

/**
 * RelBlocoUnidadeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RelBlocoUnidadeRepository extends AbstractEntityRepository
{
}
