<?php

namespace Application\Entity\Repository;

use Base\Entity\Repository\AbstractEntityRepository;
use Application;
use Doctrine\Common\Util\Debug;

/**
 * RelProtocoloProtocoloRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RelProtocoloProtocoloRepository extends AbstractEntityRepository
{
    public function pesquisarProtocoloAlternativo($protocolo)
    {
        $qb = $this->_em->createQueryBuilder();

        $qb->select('p')
            ->from('Application\Entity\RelProtocoloProtocolo', 'p')
            ->Where('p.idProtocolo1 = :protocolo')
            ->orWhere('p.idProtocolo2 = :protocolo')
            ->setParameter('protocolo', $protocolo)
            ->orderBy('p.sequencia', 'ASC');

        return $qb->getQuery()->getResult();
    }

    public function pesquisarProtocoloAtivo($protocolo)
    {
        $qb = $this->_em->createQueryBuilder();

        $qb->select('p.idProtocolo1', $qb->expr()->count('p.idUnidade'))
            ->from('Application\Entity\RelProtocoloProtocolo', 'p')
            ->Where('p.idProtocolo1 = :protocolo')
            ->setParameter('protocolo', $protocolo)
            ->groupBy('p.idProtocolo1');

        return $qb->getQuery()->getArrayResult();
    }
}
