<?php

namespace Application\Entity\Repository;

use Base\Entity\Repository\AbstractEntityRepository;
use Application;
use Application\Entity\Atividade;

/**
 * RetornoProgramadoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RetornoProgramadoRepository extends AbstractEntityRepository
{
    public function pesquisarRetornoProgramadoEnviado (Atividade $atividade) {
        $qb = $this->createQueryBuilder('P');

        $qb->where('P.idAtividadeEnvio = :atividade')
            ->setParameter('atividade', $atividade)
            ->andWhere('P.idAtividadeRetorno IS NULL');

        $qb->addOrderBy('P.dtaProgramada', 'ASC');


        return $qb->getQuery()->getResult();
    }

    public function maxRetornoProgramado() {
        $id = 0;
        $qb = $this->_em->createQueryBuilder();

        $qb->select('MAX(rp.idRetornoProgramado) AS id')
            ->from('Application\Entity\RetornoProgramado', 'rp');

        $result = $qb->getQuery()->getArrayResult();

        if (count($result))
            $id = $result[0]['id'];

        return $id;
    }
}
