<?php

namespace Application\Entity\Repository;

use Base\Entity\Repository\AbstractEntityRepository;
use Application;
use Doctrine\ORM\Tools\Pagination\Paginator;

/**
 * UnidadeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UnidadeSIPRepository extends AbstractEntityRepository
{
    public function pesquisarUnidade ($filter, $limit, $offset) {
        $qb = $this->createQueryBuilder('U');

        if ($filter) {
            $filter = strtolower($filter);

            $qb->where('LOWER(U.sigla) LIKE :filter')
                ->setParameter('filter', '%'.$filter.'%');
        }

        $qb->addOrderBy('U.sigla', 'ASC');

        $qb->setFirstResult($offset)
            ->setMaxResults($limit);

        $paginator = new Paginator($qb, true);

        return array('result' => $paginator->getQuery()->getResult(), 'count' => $paginator->count());
    }
}
