<?php

namespace Application\Entity\Repository;

use Base\Entity\Repository\AbstractEntityRepository;
use Application;

/**
 * AtividadeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UsuarioRepository extends AbstractEntityRepository
{
    public function buscarSessaoAuth($sigla)
    {
        $query = $this->createQueryBuilder('U');

        $query->where('U.sigla = :sigla')
              ->setParameter('sigla', $sigla);

        $query->setMaxResults(1);

        $result = $query->getQuery()->getResult();
        return $result ? $result[0] : null;
    }

    public function buscarUsuariosPorUnidade($unidade)
    {
        $query = $this->createQueryBuilder('U');

        $query->where('U.sigla = :sigla')
            ->setParameter('sigla', $unidade);

        $query->setMaxResults(1);

        $result = $query->getQuery()->getResult();
        return $result ? $result[0] : null;
    }
}
