<div class="col-md-12 ">
    <div class="rastro">
        <a href="<?php echo $this->url("home");?>">Home</a><i class="fa fa-angle-right"></i>
        <a href="#" class="active">Tire suas dúvidas</a>
    </div>
</div>
<div class="col-md-12 ">

    <h2>Tire suas dúvidas</h2>

    <p><strong>Sobre o sistema</strong> Lorem ipsum dolor sit amet, consectetur adipisicing elit. Aliquos mel miseram principio fonte o dicturam. Satisfacit gravissimis uterque, occultarum mundus mala praetore progrediens ibidem respirare imbutus, praetermissum optari dubio derepta desideraturam aegritudo quales. Rem facile nosmet quoddam. Geometria fruentem parta. Sic, voluptatibus torquate rationem, quidem triario impendere dulce, recordatione, faciunt defuturum sensuum, coniuncta, facile consequentium suavitate feci dicitis detrimenti, consequuntur tuentur vitiis geometrica succumbere hostem illas splendido, efficiantur omnium consentientis philosophorum, vexetur persequeretur, magnam parentes discere rutilius studium constringendos male.</p>

    <h3>Perguntas e respostas</h3>
    <div class="col-md-12 col-xs-12">
        <div class="row">
            <a class="pergunta" data-toggle="collapse" href="#col22" aria-expanded="false" aria-controls="col22">
              Pergunta
            </a>
            <div class="collapse" id="col22">
              <div class="well">
                <p><strong>Resposta</strong> Lorem ipsum dolor sit amet, consectetur adipisicing elit. Aliquos mel miseram principio fonte o dicturam. Satisfacit gravissimis uterque, occultarum mundus mala praetore progrediens ibidem respirare imbutus, praetermissum optari dubio derepta desideraturam aegritudo quales. Rem facile nosmet quoddam. Geometria fruentem parta. Sic, voluptatibus torquate rationem, quidem triario impendere dulce, recordatione, faciunt defuturum sensuum, coniuncta, facile consequentium suavitate feci dicitis detrimenti, consequuntur tuentur vitiis geometrica succumbere hostem illas splendido, efficiantur omnium consentientis philosophorum, vexetur persequeretur, magnam parentes discere rutilius studium constringendos male.</p>
              </div>
            </div>
        </div>
        <div class="row">
            <a class="pergunta" data-toggle="collapse" href="#col333" aria-expanded="false" aria-controls="col333">
              Pergunta
            </a>
            <div class="collapse" id="col333">
              <div class="well">
                <p><strong>Resposta</strong> Lorem ipsum dolor sit amet, consectetur adipisicing elit. Aliquos mel miseram principio fonte o dicturam. Satisfacit gravissimis uterque, occultarum mundus mala praetore progrediens ibidem respirare imbutus, praetermissum optari dubio derepta desideraturam aegritudo quales. Rem facile nosmet quoddam. Geometria fruentem parta. Sic, voluptatibus torquate rationem, quidem triario impendere dulce, recordatione, faciunt defuturum sensuum, coniuncta, facile consequentium suavitate feci dicitis detrimenti, consequuntur tuentur vitiis geometrica succumbere hostem illas splendido, efficiantur omnium consentientis philosophorum, vexetur persequeretur, magnam parentes discere rutilius studium constringendos male.</p>
              </div>
            </div>
        </div>
        <div class="row">
            <a class="pergunta" data-toggle="collapse" href="#col444" aria-expanded="false" aria-controls="col444">
              Pergunta
            </a>
            <div class="collapse" id="col444">
              <div class="well">
                <p><strong>Resposta</strong> Lorem ipsum dolor sit amet, consectetur adipisicing elit. Aliquos mel miseram principio fonte o dicturam. Satisfacit gravissimis uterque, occultarum mundus mala praetore progrediens ibidem respirare imbutus, praetermissum optari dubio derepta desideraturam aegritudo quales. Rem facile nosmet quoddam. Geometria fruentem parta. Sic, voluptatibus torquate rationem, quidem triario impendere dulce, recordatione, faciunt defuturum sensuum, coniuncta, facile consequentium suavitate feci dicitis detrimenti, consequuntur tuentur vitiis geometrica succumbere hostem illas splendido, efficiantur omnium consentientis philosophorum, vexetur persequeretur, magnam parentes discere rutilius studium constringendos male.</p>
              </div>
            </div>
        </div>
    </div>
</div>
