<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <title>Archetype Application - PDF Generator</title>
        <!-- Le styles -->
        <link href="/assets/application/css/style.css" media="screen" rel="stylesheet" type="text/css">
        <link href="/assets/vendor/bootstrap/css/bootstrap-responsive.min.css" media="screen" rel="stylesheet" type="text/css">
        <link href="/assets/application/img/favicon.ico" rel="shortcut icon" type="image/vnd.microsoft.icon">
        <link href="/assets/vendor/bootstrap/css/bootstrap.min.css" media="screen" rel="stylesheet" type="text/css">
    </head>
    <body>
        <div class="container">
            <div class="row">
                <div class="col-md-offset-1 col-md-7">
                    <?php echo $legend ?>
                </div>
            </div>
            <div class="hero-unit">
                <h1><?php echo $title ?></h1>
                <p>Este é um exemplo de geração de PDF utilizando o componente DOMPDF.</p>
                <p><a class="btn btn-success btn-large" href="https://packagist.org/packages/dino/dompdf-module" target="_blank">DOMPDF-Module &raquo;</a></p>
            </div>
            <hr>
        </div>
    </body>
</html>
