<h1>Teste</h1>
<table class="table table-striped">
    <thead>
        <tr>
            <th>CO_FUNCAO</th>
            <th>NO_FUNCAO</th>
            <th>DS_FUNCAO</th>
        </tr>
    </thead>
    <tbody>
    <?php  foreach ($paginator as $result) : ?>
        <tr>
            <td><?php echo $result->getCoFuncao() ?></td>
            <td><?php echo $result->getNoFuncao() ?></td>
            <td><?php echo $result->getDsFuncao() ?></td>
        </tr>
    <?php endforeach; ?>
    </tbody>
</table>
<?php
    echo $this->paginationControl($paginator, null, null, array('url' => $this->basePath('/index/teste')));
?>
