# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class Test013SIPPermissoes():
  def setup_method(self, method):
    self.driver = webdriver.Remote(command_executor='http://seleniumhub:4444/wd/hub', desired_capabilities=DesiredCapabilities.CHROME)
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_sIPPermissaoUsuario2UnTeste2x50(self):
    self.driver.get("http://sei3.nuvem.gov.br//sip/login.php?sigla_orgao_sistema=ME&sigla_sistema=SIP")
    self.driver.find_element(By.ID, "txtUsuario").send_keys("teste")
    self.driver.find_element(By.ID, "pwdSenha").click()
    self.driver.find_element(By.ID, "pwdSenha").send_keys("teste")
    self.driver.find_element(By.ID, "sbmLogin").click()
    self.vars["iLoop"] = self.driver.execute_script("return 2")
    for i in range(0, 50):
      self.vars["iLoop"] = self.driver.execute_script("return arguments[0] +1", self.vars["iLoop"])
      WebDriverWait(self.driver, 30000).until(expected_conditions.visibility_of_element_located((By.XPATH, "//ul[@id=\'main-menu\']/li[1]/a")))
      self.driver.find_element(By.XPATH, "//ul[@id=\'main-menu\']/li[1]/a").click()
      print(str("un6"))
      self.driver.find_element(By.LINK_TEXT, "Nova").click()
      WebDriverWait(self.driver, 30000).until(expected_conditions.element_to_be_clickable((By.ID, "selOrgaoSistema")))
      self.driver.find_element(By.ID, "selOrgaoSistema").click()
      dropdown = self.driver.find_element(By.ID, "selOrgaoSistema")
      dropdown.find_element(By.XPATH, "//option[. = 'ME']").click()
      self.driver.find_element(By.ID, "selOrgaoSistema").click()
      WebDriverWait(self.driver, 30000).until(expected_conditions.element_to_be_clickable((By.ID, "selSistema")))
      dropdown = self.driver.find_element(By.ID, "selSistema")
      dropdown.find_element(By.XPATH, "//option[. = 'SEI']").click()
      self.driver.find_element(By.ID, "selSistema").click()
      WebDriverWait(self.driver, 30000).until(expected_conditions.element_to_be_clickable((By.ID, "selOrgaoUnidade")))
      self.driver.find_element(By.ID, "selOrgaoUnidade").click()
      dropdown = self.driver.find_element(By.ID, "selOrgaoUnidade")
      dropdown.find_element(By.XPATH, "//option[. = 'ME']").click()
      self.driver.find_element(By.ID, "selOrgaoUnidade").click()
      WebDriverWait(self.driver, 30000).until(expected_conditions.element_to_be_clickable((By.ID, "selUnidade")))
      dropdown = self.driver.find_element(By.ID, "selUnidade")
      dropdown.find_element(By.CSS_SELECTOR, "*[value='110000003']").click()
      self.driver.find_element(By.ID, "selUnidade").click()
      self.driver.find_element(By.ID, "selOrgaoUsuario").click()
      dropdown = self.driver.find_element(By.ID, "selOrgaoUsuario")
      dropdown.find_element(By.XPATH, "//option[. = 'ME']").click()
      self.driver.find_element(By.ID, "selOrgaoUsuario").click()
      self.driver.find_element(By.ID, "txtUsuario").click()
      print(str("aqui"))
      self.driver.find_element(By.ID, "txtUsuario").clear()
      self.driver.find_element(By.ID, "txtUsuario").send_keys("usuario" + str(self.vars["iLoop"]))
      # self.driver.save_screenshot("teste.png")
      WebDriverWait(self.driver, 30000).until(expected_conditions.visibility_of_element_located((By.CSS_SELECTOR, "b:nth-child(1)")))
      element = self.driver.find_element(By.CSS_SELECTOR, "b:nth-child(1)")
      actions = ActionChains(self.driver)
      actions.move_to_element(element).click_and_hold().perform()
      element = self.driver.find_element(By.ID, "divInfraAreaDados")
      actions = ActionChains(self.driver)
      actions.move_to_element(element).release().perform()
      self.driver.find_element(By.CSS_SELECTOR, "body").click()
      self.driver.find_element(By.ID, "selPerfil").click()
      dropdown = self.driver.find_element(By.ID, "selPerfil")
      dropdown.find_element(By.XPATH, "//option[. = 'Básico']").click()
      self.driver.find_element(By.NAME, "sbmCadastrarPermissao").click()
  
