name: Testes da API

on: [pull_request]
env: # Or as an environment variable
  NEWMAN_BASEURL: 'http://localhost:8000'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Fetch Pull Request branch
        uses: actions/checkout@v3
        with:
            repository: pengovbr/sei
            token: ${{ secrets.GH_PAT }} # `GH_PAT` is a secret that contains your PAT
            path: sei
            ref: 5.0.3
      - name: Checkout
        uses: actions/checkout@v3
        with:
            path: sei/src/sei/web/modulos/mod-wssei

      - name: Run make test
        run: | 
             cd sei/src/sei/web/modulos/mod-wssei
             make tests-api
