# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class Test012SEIModWsseiSIP():
  def setup_method(self, method):
    self.driver = webdriver.Remote(command_executor='http://seleniumhub:4444/wd/hub', desired_capabilities=DesiredCapabilities.CHROME)
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_criarUsuariosx50(self):
    self.driver.get("http://sei3.nuvem.gov.br/sip/login.php?sigla_orgao_sistema=ME&sigla_sistema=SIP&infra_url=L3NpcC8=")
    self.driver.find_element(By.ID, "txtUsuario").click()
    self.driver.find_element(By.ID, "txtUsuario").send_keys("teste")
    self.driver.find_element(By.ID, "pwdSenha").click()
    self.driver.find_element(By.ID, "pwdSenha").send_keys("teste")
    self.driver.find_element(By.ID, "sbmLogin").click()
    self.vars["iLoop"] = self.driver.execute_script("return 2")
    for i in range(0, 50):
      self.vars["iLoop"] = self.driver.execute_script("return arguments[0] + 1", self.vars["iLoop"])
      WebDriverWait(self.driver, 30000).until(expected_conditions.visibility_of_element_located((By.XPATH, "//*[@id=\"main-menu\"]/li[6]/a")))
      self.driver.find_element(By.XPATH, "//*[@id=\"main-menu\"]/li[6]/a").click()
      self.driver.find_element(By.LINK_TEXT, "Novo").click()
      WebDriverWait(self.driver, 30000).until(expected_conditions.element_to_be_clickable((By.ID, "selOrgao")))
      self.driver.find_element(By.ID, "divInfraAreaDados").click()
      self.driver.find_element(By.ID, "selOrgao").click()
      dropdown = self.driver.find_element(By.ID, "selOrgao")
      dropdown.find_element(By.XPATH, "//option[. = 'ME']").click()
      self.driver.find_element(By.ID, "selOrgao").click()
      self.driver.find_element(By.ID, "txtSigla").click()
      self.driver.find_element(By.ID, "txtSigla").send_keys("usuario" + str(self.vars["iLoop"]))
      self.driver.find_element(By.ID, "txtNome").click()
      self.driver.find_element(By.ID, "txtNome").send_keys("Usuario de Teste " + str(self.vars["iLoop"]))
      self.driver.find_element(By.NAME, "sbmCadastrarUsuario").click()
  
